#! /bin/sh

. /lib/lsb/init-functions

name="logstash-agent"
logstash_bin="/opt/logstash/logstash.jar"
logstash_conf="/opt/logstash/sample_shipper.conf"
logstash_log="/var/log/logstash/agent.log"
java_bin="/usr/bin/java"
pid_file="/var/run/$name.pid"
cwd=`pwd`

start () {
        command="${java_bin} -- -jar ${logstash_bin} -- agent -f $logstash_conf -l ${logstash_log}" 

        log_daemon_msg "Starting $name"
        if start-stop-daemon --start --quiet --oknodo --pidfile "$pid_file" -b -m -N 19 --exec $command; then
                log_end_msg 0
        else
                log_end_msg 1
        fi
}

stop () {
        log_daemon_msg "Stopping $name"
        start-stop-daemon --stop --quiet --oknodo --pidfile "$pid_file"
}

status () {
        status_of_proc -p $pid_file "" "$name"
}

case $1 in
        start)
                if status; then exit 0; fi
                start
                ;;
        stop)
                stop
                ;;
        reload)
                stop
                sleep 2
                start
                ;;
        restart)
                stop
                sleep 2
                start
                ;;
        status)
                status && exit 0 || exit $?
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|reload|status}"
                exit 1
                ;;
esac

exit 0
