#! /bin/sh
# /etc/init.d/logstash-shipper-init
#
. /lib/lsb/init-functions
# run always
if [ "$1" = "" ]
then
  service elasticsearch start
  service redis-server start
  service logstash start
  
fi
case "$1" in
  start)
    echo "Starting logstash-shipper-init"
    service elasticsearch start
    service redis-server start
    service logstash start
  
    ;;
  stop)
    echo "Stopping logstash-shipper-init"
  
    service logstash stop
    service elasticsearch stop
    service redis-server stop
    ;;
  status)
    service logstash status
    service elasticsearch status
    service redis-server status
  
    ;;
  restart)
    service elasticsearch restart
    service redis-server restart
    service logstash restart
  
    ;;
  *)
    echo "Usage: /etc/init.d/logstash-shipper-init {start|stop|status|restart}"
    exit 1
    ;;
esac

exit 0
