#! /bin/sh
# /etc/init.d/logstash-agent
#

# run always
service redis-server start
service elasticsearch start
service logstash start
case "$1" in
  start)
    echo "Starting logstash-all"
    service redis-server start
    service elasticsearch start
    service logstash start
    ;;
  stop)
    echo "Stopping logstash-all"
    service logstash stop
    service elasticsearch stop
    service redis-server stop
    ;;
  status)
    service logstash status
    service elasticsearch status
    service redis-server status
    ;;
  restart)
    service logstash restart
    service elasticsearch restart
    service redis-server restart
    ;;
  *)
    echo "Usage: /etc/init.d/logstash-agent-init {start|stop|status|restart}"
    exit 1
    ;;
esac

exit 0
